INSERT INTO user_profiles (name, created_at) VALUES
    ('DEVELOPER', NOW()),
    ('RECRUITER', NOW());

INSERT INTO url_supported_platforms (name, label, logo, created_at, updated_at) VALUES
    ('linkedin', 'LinkedIn', '', NOW(), NOW()),
    ('github', 'Github', '', NOW(), NOW());

INSERT INTO skills (name, created_at) VALUES
    ('Frontend', NOW()),
    ('Backend', NOW()),
    ('FullStack', NOW()),
    ('DevOps', NOW()),
    ('Java', NOW()),
    ('Java EE', NOW()),
    ('Java ME', NOW()),
    ('Java SE', NOW()),
    ('JavaFX', NOW()),
    ('Java Card', NOW()),
    ('Java TV', NOW()),
    ('Swing', NOW()),
    ('AWT', NOW()),
    ('Spring', NOW()),
    ('SpringBoot', NOW()),
    ('JDBC', NOW()),
    ('JPA', NOW()),
    ('Hibernate', NOW()),
    ('Spring Security', NOW()),
    ('Junit', NOW()),
    ('Mockito', NOW()),
    ('Cucumber', NOW()),
    ('Spring Batch', NOW()),
    ('Spring Cloud', NOW()),
    ('Socket', NOW()),
    ('Rest', NOW()),
    ('Soap', NOW()),
    ('JSON', NOW()),
    ('XML', NOW()),
    ('YML', NOW()),
    ('Markdown', NOW()),
    ('HTML', NOW()),
    ('CSS', NOW()),
    ('SASS', NOW()),
    ('SCSS', NOW()),
    ('Javascript', NOW()),
    ('Typescript', NOW()),
    ('jQuery', NOW()),
    ('React', NOW()),
    ('React Native', NOW()),
    ('Next JS', NOW()),
    ('Remix', NOW()),
    ('Vue JS', NOW()),
    ('Nuxt JS', NOW()),
    ('Angular JS', NOW()),
    ('Angular', NOW()),
    ('Svelte', NOW()),
    ('Node JS', NOW()),
    ('Express JS', NOW()),
    ('Nest JS', NOW()),
    ('LoopBack JS', NOW()),
    ('Adonis JS', NOW()),
    ('Deno', NOW()),
    ('Bun', NOW()),
    ('Python', NOW()),
    ('Django', NOW()),
    ('Flask', NOW()),
    ('Odoo', NOW()),
    ('Ruby', NOW()),
    ('Ruby on Rails', NOW()),
    ('PHP', NOW()),
    ('Laravel', NOW()),
    ('Symfony', NOW()),
    ('WordPress', NOW()),
    ('PrestaShop', NOW()),
    ('C', NOW()),
    ('C++', NOW()),
    ('C#', NOW()),
    ('.NET', NOW()),
    ('VB.NET', NOW()),
    ('ASP.NET', NOW()),
    ('Rust', NOW()),
    ('Go', NOW()),
    ('Android Natif', NOW()),
    ('Kotlin', NOW()),
    ('Swift', NOW()),
    ('Objective-C', NOW()),
    ('Dart', NOW()),
    ('Flutter', NOW()),
    ('Ionic', NOW()),
    ('Cordova', NOW()),
    ('PhoneGap', NOW()),
    ('Xamarin', NOW()),
    ('Unity', NOW()),
    ('Unreal Engine', NOW()),
    ('Godot', NOW()),
    ('Clean Code', NOW()),
    ('SOLID principles', NOW()),
    ('Design paterns', NOW()),
    ('Clean Architecture', NOW()),
    ('Hexagonale Architecture', NOW()),
    ('TDD', NOW()),
    ('BDD', NOW()),
    ('DDD', NOW()),
    ('Microservices', NOW()),
    ('Docker', NOW()),
    ('Kubernetes', NOW()),
    ('Jenkins', NOW()),
    ('AWS', NOW()),
    ('GCP', NOW()),
    ('Azure', NOW()),
    ('CI/CD', NOW()),
    ('Git', NOW()),
    ('Agile Method', NOW()),
    ('Agile Scrum', NOW());



